name: Build Nikki

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic-openwrt-24.10
          - aarch64_cortex-a72-openwrt-24.10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki
          NO_REFRESH_CHECK: true

      - name: Pack artifacts
        run: |
          mkdir -p artifacts/${{ matrix.arch }}
          find bin -name '*nikki*.ipk' -exec cp -v {} artifacts/${{ matrix.arch }}/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nikki-${{ matrix.arch }}
          path: artifacts/${{ matrix.arch }}